name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest  # Since you're using Windows

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Add testing framework
    
    - name: Create directories
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
        mkdir -p data/sample
    
    - name: Run tests
      run: |
        python -m pytest tests/
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          test-results/
          coverage/
